Fix clippy error `absurd_extreme_comparisons`
* `event_per_sample` is a `u32` so it can never be greater than `u32::MAX` or less than `u32::MIN`. I see the reason for the check, though, since `let start_value = core::u32::MAX - event_per_sample` hardcodes the `u32` type; it's not tied to `event_per_sample`'s type. As such I left the check in place and added an `#[allow(...)]` attribute to disable the clippy warning.

* I added a special check for `event_per_sample == 0` and gave it its own error message saying that values must be nonzero.

* Note that I changed the `<= u32::MIN` comparison to `< u32::MIN`.

```
error: this comparison involving the minimum or maximum element for this type contains a case that is always true or always false
   --> kernel/pmu_x86/src/lib.rs:693:8
    |
693 |     if event_per_sample > core::u32::MAX || event_per_sample <= core::u32::MIN {
    |        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    |
    = note: `#[deny(clippy::absurd_extreme_comparisons)]` on by default
    = help: because `core::u32::MAX` is the maximum value for this type, this comparison is always false
    = help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#absurd_extreme_comparisons

error: this comparison involving the minimum or maximum element for this type contains a case that is always true or always false
   --> kernel/pmu_x86/src/lib.rs:693:45
    |
693 |     if event_per_sample > core::u32::MAX || event_per_sample <= core::u32::MIN {
    |                                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    |
    = help: because `core::u32::MIN` is the minimum value for this type, the case where the two sides are not equal never occurs, consider using `event_per_sample == core::u32::MIN` instead
    = help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#absurd_extreme_comparisons
```