Fix clippy lint `derive_hash_xor_eq`
* `TaskRef` implements `PartialEq` by comparing pointers. `Hash` needs to match that behavior.

```
error: you are deriving `Hash` but have implemented `PartialEq` explicitly
    --> kernel/task/src/lib.rs:864:24
     |
864  | #[derive(Debug, Clone, Hash)]
     |                        ^^^^
     |
     = note: `#[deny(clippy::derive_hash_xor_eq)]` on by default
note: `PartialEq` implemented here
    --> kernel/task/src/lib.rs:1021:1
     |
1021 | / impl PartialEq for TaskRef {
1022 | |     fn eq(&self, other: &TaskRef) -> bool {
1023 | |         Arc::ptr_eq(&self.0, &other.0)
1024 | |     }
1025 | | }
     | |_^
     = help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#derive_hash_xor_eq
     = note: this error originates in the derive macro `Hash` (in Nightly builds, run with -Z macro-backtrace for more info)
```